version: "3.7"

services: 
  database:
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fieldbot
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
  
  web:
    build: .
    image: fieldbot/server:latest
    depends_on:
      - database
    restart: always
    ports:
      - "3000:3000"
    links:
      - "database"
    environment:
      DB_HOST: database
      ENVIRONMENT: development
      PORT: 3000